#---------------------------------------------
# This script reads data from two processed .csv files,
# 'trip_data_proc.csv' and 'trip_data_station_name_proc.csv'.

# In df read from 'trip_data_proc.csv', 'ride_length' is grouped
# by the following column name(s), and output the corresponding sub-dataframe to path,
# year, called it stat_yr,
# month, called it stat_month,
# day_of_week, called it stat_day_of_week,
# hour_of_day, called it stat_hour_of_day,
# member_casual, called it stat_user,
# member_casual and month, called it stat_user_month,
# member_casual and day_of_week, called it stat_user_day_of_week,
# member_casual and hour_of_day, called it stat_user_hour_of_day.
# member_causal and rideable_type, called it stat_user_rideable_type

# In df read from 'trip_data_station_name_proc.csv', ride count percentage of every rider type
# in every station was obtained. Output df was generated by sorting the ride count perct in
# descending order for each rider type. Note, only stations with ride count >= mean ride count
# of each rider type were included in the output dfs.
#---------------------------------------------

# load packages
library(tidyr)
library(dplyr)
library(lubridate)
#library(tidyverse) 

# specify path where input data are
path_req <- '/home/siumichael.tang/bike_share/data_r/'

# enter processed trip data filename
filename_tripdata <- 'trip_data_proc.csv'
filename_tripdata_station_name = 'trip_data_station_name_proc.csv'

# read processed trip data
df_tot <- read.csv(paste(path_req, filename_tripdata, sep = ''))
df_tot_station_name <- read.csv(paste(path_req, filename_tripdata_station_name, sep = ''))

# compute mean and max ride length, and number of rides, for each of the 
# following levels:
# by (i) year, (ii) month, (iii) day of week, (iv) hour of day, and (v) user type,
# then further group stats by
# (v) and (ii), (v) and (iii), (v) and (iv)

# by year
stat_yr <- summarize(df_tot, mean_ride_length = mean(ride_length),
                     max_ride_length = max(ride_length), ride_count = n())

# by month
stat_month <- df_tot %>% group_by(month_of_yr) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# create customized month_order to denote months go from May to Dec, then Jan to Apr
month_levels <- c(5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4)

# updating stat_month by using factor() to convert 'month_of_yr' as factor var with levels
# specified by month_levels, then by using arrange() to apply customized month order
# to column 'month_of_yr' to reorder the tibble
stat_month <- stat_month %>% arrange(factor(month_of_yr, levels = month_levels))

# by day of week when trip started
stat_day_of_week <- df_tot %>% group_by(day_of_week) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# by hour of day when trip started
stat_hour_of_day <- df_tot %>% group_by(hour_of_day) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# by user type 
stat_user <- df_tot %>% group_by(member_casual) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# by user type and month
stat_user_month <- df_tot %>% group_by(member_casual, month_of_yr) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# updating stat_user_month by using factor() to convert 'month_of_yr' as factor var with levels
# specified by month_levels, then by using arrange() to apply customized month order
# to column 'month_of_yr' to reorder the tibble
stat_user_month <- stat_user_month %>% arrange(factor(month_of_yr, levels = month_levels))

# by user type and day of week
stat_user_day_of_week <- df_tot %>% group_by(member_casual, day_of_week) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# by user type and hour of day
stat_user_hour_of_day <- df_tot %>% group_by(member_casual, hour_of_day) %>%
  summarize(mean_ride_length = mean(ride_length), 
            max_ride_length = max(ride_length), ride_count = n())

# by user type and rideable type
stat_user_rideable_type <- df_tot %>% group_by(member_casual, rideable_type) %>%
  summarize(mean_ride_length = mean(ride_length),
            max_ride_length = max(ride_length), ride_count = n())

# get ride count percentage (in descending order) of each rider type in every station:

# group rows by columns, member_casual and start_station_name, and get their ride count
df_user_start_station_name <- df_tot_station_name %>% group_by(member_casual, start_station_name) %>%
    summarize(ride_count = n())

# obtain subsets of the grouped dataframe as df_casual_user_station and df_member_user_station, where
# df_casual_user_station contains ride count of casual riders for each station, while
# df_casual_member_station contains ride count of member riders for each station
df_casual_user_station <- subset(df_user_start_station_name, member_casual == 'casual')
df_member_user_station <- subset(df_user_start_station_name, member_casual == 'member')

# perform inner join between the two dataframes on column 'start_station_name', store result in df_user_station_merged
# df_user_station_merged contains ride counts of casual and member riders of every station
df_user_station_merged <- inner_join(df_casual_user_station, df_member_user_station, by = 'start_station_name')
df_user_station_merged <- inner_join(df_casual_user_station, df_member_user_station, by = 'start_station_name',
    suffix = c('_casual', '_member'))


# get percentage of ride count by rider type for every station, store values under new column named
# 'ride_count_perct_casual' and 'ride_count_perct_member'
df_user_station_merged['ride_count_perct_casual'] <-
    df_user_station_merged['ride_count_casual'] / (df_user_station_merged['ride_count_casual'] +
                                                   df_user_station_merged['ride_count_member'])

df_user_station_merged['ride_count_perct_member'] <-
    df_user_station_merged['ride_count_member'] / (df_user_station_merged['ride_count_casual'] +
                                                   df_user_station_merged['ride_count_member'])

# obtain mean ride count across all stations for each rider type
mean_ride_count_casual <- mean(df_user_station_merged[['ride_count_casual']])
mean_ride_count_member <- mean(df_user_station_merged[['ride_count_member']])

# filter df_user_station_merged by selecting rows with
# (i) ride_count_casual >= mean_ride_count_casual, and
# (ii) ride_count_member >= mean_ride_count_member,
# store filtered df in df_user_station_filtered
# df_user_station_filtered contains ride count for each rider type only for stations with ride counts >= mean ride
# count of each rider type
df_user_station_filtered <- subset(df_user_station_merged, ride_count_casual >= mean_ride_count_casual &
    ride_count_member >= mean_ride_count_member)

# sort ride count percentage of each rider type in descending order, store resultant df in
# stat_casual_station_filtered_sorted and stat_member_station_filtered_sorted
# stat_casual(OR member)_station_filtered_sorted contains ride count for every station that has ride count >= mean ride
# count of each rider type, and rows are sorted in descending order of casual(OR member) ride count percentage,
stat_casual_station_filtered_sorted <-
    df_user_station_filtered[order(df_user_station_filtered$ride_count_perct_casual, decreasing = TRUE),]

stat_member_station_filtered_sorted <-
    df_user_station_filtered[order(df_user_station_filtered$ride_count_perct_member, decreasing = TRUE),]

# note: stations with high ride count percentages for each rider type did not necessarily mean that the stations
# were popular among riders, therefore, only those with ride count >= mean ride count of every rider type were
# considered. Afterward, the df was sorted in descending order by ride count percentage of each rider type,
# generating one df for casual riders (i.e. stat_casual_station_filtered_sorted) and one for
# member riders (i.e. stat_member_station_filtered_sorted).


# write tibbles obtained above in .csv files, save files to path specified below
filedir_op <- '/home/siumichael.tang/bike_share/data_r/'

filename_op_month <- 'stat_month.csv'
filename_op_day_of_week <- 'stat_day_of_week.csv'
filename_op_hour_of_day <- 'stat_hour_of_day.csv'
filename_op_user <- 'stat_user.csv'
filename_op_user_month <- 'stat_user_month.csv'
filename_op_user_day_of_week <- 'stat_user_day_of_week.csv'
filename_op_user_hour_of_day <- 'stat_user_hour_of_day.csv'
filename_op_user_rideable_type <- 'stat_user_rideable_type.csv'
filename_op_casual_station_filtered_sorted <- 'stat_casual_station_filtered_sorted.csv'   # output filename of stat_casual_station_filtered_sorted
filename_op_member_station_filtered_sorted <- 'stat_member_station_filtered_sorted.csv'   # output filename of stat_member_station_filtered_sorted

# write tibbles to .csv files for further viz making
write.csv(stat_month, file.path(filedir_op, filename_op_month), row.names = FALSE)   # save stat_day_of_week to path, remove row index
write.csv(stat_day_of_week, file.path(filedir_op, filename_op_day_of_week), row.names = FALSE)   # save stat_hour_of_day to path, remove row index
write.csv(stat_hour_of_day, file.path(filedir_op, filename_op_hour_of_day), row.names = FALSE)   # save stat_user_hour_of_day to path, remove row index

write.csv(stat_user_month, file.path(filedir_op, filename_op_user_month), row.names = FALSE)   # save stat_user_month to path, remove row index
write.csv(stat_user_day_of_week, file.path(filedir_op, filename_op_user_day_of_week), row.names = FALSE)   # save stat_user_day_of_week to path, remove row index
write.csv(stat_user_hour_of_day, file.path(filedir_op, filename_op_user_hour_of_day), row.names = FALSE)   # save stat_user_hour_of_day to path, remove row index
write.csv(stat_user_rideable_type, file.path(filedir_op, filename_op_user_rideable_type), row.names = FALSE)   # save stat_user_rideable_type to path, remove row index

write.csv(stat_casual_station_filtered_sorted, file.path(filedir_op, filename_op_casual_station_filtered_sorted), row.names = FALSE)   # save stat_casual_station_filtered_sorted to path, remove row index
write.csv(stat_member_station_filtered_sorted, file.path(filedir_op, filename_op_member_station_filtered_sorted), row.names = FALSE)   # save stat_member_station_filtered_sorted to path, remove row index

# print message to console
print('done analyzing data and outputting dataframes')